### ISSUE TITLE
NodeGit on travis Error: Cannot find module '../build/Debug/nodegit.node'

### ISSUE THREAD

**Issue by thisconnect** [thisconnect/nodegit-kit#15]
travis build `Error: Cannot find module '../build/Debug/nodegit.node'`

```bash
module.js:327
    throw err;
    ^
Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/thisconnect/nodegit-kit/node_modules/nodegit/dist/nodegit.js:18:12)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at extensions.(anonymous function) (/home/travis/build/thisconnect/nodegit-kit/node_modules/ava/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/thisconnect/nodegit-kit/node_modules/ava/lib/test-worker.js:89:3)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/thisconnect/nodegit-kit/lib/config.js:3:11)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
```

**Comment by thisconnect** [comment]
Fixed with https://github.com/thisconnect/nodegit-kit/blob/4087a7baa0e51986f31ccbd902e9ce6367a40559/.travis.yml
