### ISSUE TITLE
nodegit 0.5.0 on travis fails on Node 4.x

### ISSUE THREAD

**Issue by thisconnect** [thisconnect/nodegit-kit#8]
Note: Node.js 5.0.0 is fine

Related: 
- Failed to fetch from (https://github.com/nodegit/nodegit/issues/736)
- Static link to glibc (https://github.com/nodegit/nodegit/issues/585)

https://travis-ci.org/thisconnect/nodegit-kit/builds/89676720

```bash
> nodegit-kit@0.0.5 test /home/travis/build/thisconnect/nodegit-kit
> tape ./test/test.js | tap-spec
/home/travis/build/thisconnect/nodegit-kit/node_modules/nodegit/lib/nodegit.js:13
    throw ex;
    ^
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /home/travis/build/thisconnect/nodegit-kit/node_modules/nodegit/build/Release/nodegit.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/travis/build/thisconnect/nodegit-kit/node_modules/nodegit/lib/nodegit.js:8:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
  ✖ No tests found
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
Done. Your build exited with 1.
```

**Comment by thisconnect** [comment]
Good with Node.js 5.0.0 
https://travis-ci.org/thisconnect/nodegit-kit/builds/89731711
https://github.com/thisconnect/nodegit-kit/blob/7ec80351f5075c83f5fd8ffdfa43603c57b18f39/.travis.yml

**Comment by thisconnect** [comment]
Wohooo passes on Node v4 and v5, changed setting to `BUILD_ONLY=true npm install` in  https://github.com/thisconnect/nodegit-kit/commit/3268b348ab08101f4cc40da82fe1e0f5a8dc156e
  
https://travis-ci.org/thisconnect/nodegit-kit/builds/89813887

**Comment by thisconnect** [comment]
https://github.com/thisconnect/nodegit-kit/commit/eec1ff67a4fae19861436855bc2a4bfc5fa88e88 did not rebuild and was much faster https://travis-ci.org/thisconnect/nodegit-kit/builds/89817896
